### ISSUE TITLE
Custom tabs not saving

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-area-tabs#41]
There seems to still be an issue where custom tabs don't save properly. A customer had 3 custom tabs and after adding 2 more in a row, the last 2 did not save. Adding them one by one seems to get around the issue. Will try and replicate.

**Comment by sumobi** [comment]
To replicate:

1. Make sure there are 3 custom tabs set up. Indexes should be 0, 1 and 2 as expected.
2. Remove the first tab by clicking the `x` to the far right but don't save. The indexes that remain are now 1 and 2.
3. Add a new custom tab and save. The indexes become 1, 2 and 2.
4. The now second tab is wiped out completely since the last tab has the same index as the second.

**Comment by pippinsplugins** [comment]
This should be able to be fixed by simply re-indexing on each save.

**Comment by gspice** [comment]
Re-tested, this still occurs with the latest AffiliateWP/AffiliateWP#1693 and AAT changes.

**Comment by amdrew** [comment]
This should be fixed with v1.2.
